name: meins_endercraft
version: '1.22'
main: de.ender.endercraft.Main
api-version: 1.19
load: POSTWORLD
depend: [ meins_core ]
authors: [ ender__exe ]
description: Endercraft
website: https://github.com/github-dotEXE

commands:
  heal:
    description: /heal!
  sudo:
    description: /sudo <Player> <Command...>!
  flyspeed:
    description: /flyspeed <1-100>! 10 is Default!
  fly:
    description: /fly!
  godmode:
    description: /godmode!
  ec:
    description: /ec!
  craft:
    description: /craft!
  invsee:
    description: /invsee <Player>!
  vanish:
    description: /vanish!
  chat:
    description: /chat <Massage>!
  enchantitem:
    description: /enchantitem <enchantment> <level>!
  position:
    description: /position set|get|del|list|pos <name>!
  setspawn:
    description: /setspawn! After you set the Spawn You'll spawn there when you join the Server!
  delspawn:
    description: /delspawn!
  spawn:
    description: /spawn!
  realtime:
    description: /realtime!
  rename:
    description: /rename <Name...>! You can use "&" for Color-Codes!
  itemlock:
    description: /itemlock <Code>!
  repair:
    description: /repair!
  floatsign:
    description: /floatsign <Color> <..TEXT..>
  glide:
      description: /glide
  statistics:
    description: /statistics <PlayerTarget> <Statistic>
  advancementprogress:
    description: /advancementprogress <PlayerTarget> <Statistic>
  nick:
    description: /nick
  clr:
    description: /clr clears inv
  i:
    description: /i
  resetworld:
    permission: endercraft.resetworld
  demomode:
    permission: endercraft.demomode